### PR TITLE
#4 Create a custom byte array serializer

### PR DESCRIPTION
**Pull request by nickmcdowall**
Override default behaviour of fields that are byte[] so that we display the String value instead (and prettyPrint if appears to be json).

### CODE REVIEW

**Comment by lukasz-gryzbon** [comment]
I see what you mean now.

Looks goods to me. There may be some edge cases to test though.

👍

**Comment by nickmcdowall** [comment]
Hey dude,

I have noticed that since I merged in the latest changes from main the formatting doesn't appear to render as well anymore.

As an example - when using the new byte array serializer that contains a json payload here is a comparison:

* after merging in the latest changes:

```
an object with bytes[] field.[4] = {
  "value": {
  "name": "Bond",
  "age": 64
}
}
```


* before merging in the recent changes we could produce this output:
```
an object with bytes[] field.[4] = {
  "value": {
    "name": "Bond",
    "age": 64
  }
}
```

I also had to remove the inclusion of the object type from the output since a plain json string would start adding LinkedHashMap as a key so dropped that while merging too.

**Comment by lukasz-gryzbon** [comment]
That's strange. 

I had to switch from GSON to JACKSON (ObjectMapper) as I couldn't find a setting for GSON to pretty print arrays in a single line. But that should not break the formatting... it probably did though... 😞

**Review by lukasz-gryzbon — APPROVED** [review]

**Comment by nickmcdowall** [comment]
Hey dude, 

Merged in the changes from `main` and resolved the conflicts. We should now see byte[] fields converted to strings and pretty printed if they are json. As mentioned before the formatting doesn't seem to be as 'pretty' as it could be but it's an improvement for now.

Example generated which includes byte[] containing json for reference:
```
{
  "value": 2,
  "exampleObjectWithBytes": {
    "value": {
  "name": "Bond",
  "age": 164,
  "hungry": true
}
  },
  "exampleObject": {
    "value": 5
  }
}
```

Another thought is that the byte[] content could be xml too which would need pretty printing

**Pull request merged**
